### ISSUE TITLE
Alert bar should be able to be scheduled

### ISSUE THREAD

**Issue by polevaultweb** [deliciousbrains/wp-alert-bars#17]
We no longer have the option to schedule an alert bar 

![image](https://user-images.githubusercontent.com/1770201/141776613-19d5774a-1b86-4483-8be9-df2374702367.png)

**Comment by sanjucta** [comment]
@polevaultweb 
There's an 'Alert Bar Date' meta-box that has a field called 'end' that deletes the alert bar at the scheduled time. 

![image](https://user-images.githubusercontent.com/4763997/141791875-8ddf2a43-a1a8-45de-82f0-8fab63642fe1.png)

This functionality seems to be working, atleast locally, on the dbi site. Are you referring to something else?

**Comment by polevaultweb** [comment]
My test site must be using an older version of the package, I didn't seen the 'Edit' link for the publish date (to control when the alert bar goes live). All good
